name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t xsmity01/task-backend:latest .

    - name: Push Docker image
      run: docker push xsmity01/task-backend:latest

    - name: Tag Docker image with version
      run: docker tag xsmity01/task-backend:latest xsmity01/task-backend:version${{ github.run_number }}

    - name: Push Docker image tag:version
      run: docker push xsmity01/task-backend:version${{ github.run_number }}